name: Check PR Comment

on:
  issue_comment:
    types:
      - "created"
      - "edited"

env:
  CARGO_TERM_COLOR: always

jobs:
  check_triggers:
    name: Check presence of trigger-words
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      rebuild: ${{ steps.rebuild.ouputs.rebuild }}
      retest: ${{ steps.retest.outputs.retest }}
    steps:
    - name: Print comment body
      run: |
        echo ${{ github.event.comment.body }}
    - name: Check if rebuild is requested
      id: rebuild
      if: ${{ github.event.comment.body == 'rebuild'}}
      run: echo "::set-output name=rebuild::true"
    - name: Check if retest is requested
      id: retest
      if: ${{ github.event.comment.body == 'retest'}}
      run: echo "::set-output name=retest::true"
  summarize_triggers:
    name: Summarize results of checking trigger-words
    runs-on: ubuntu-latest
    needs: check_triggers
    steps:
      - name: Print selections
        run: echo "Rebuild = ${{ needs.check_triggers.output.rebuild }}; Retest = ${{ needs.check_triggers.output.retest }} "