name: Check PR Comment

on:
  issue_comment:
    types:
      - "created"
      - "edited"

env:
  CARGO_TERM_COLOR: always

jobs:
  check_triggers:
    name: Check presence of trigger-words
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check_rebuild
        with:
          trigger: 'rebuild'
      - uses: khan/pull-request-comment-trigger@master
        id: check_retest
        with:
          trigger: 'retest'
      - run: 'echo Rebuild requested!'
        if: steps.check_rebuild.outputs.triggered == 'true'
      - run: 'echo Retest requested!'
        if: steps.check_retest.outputs.triggered == 'true'
